export const DIET_TYPES = [
  { key: "general", label: "General", emoji: "\uD83C\uDF7D\uFE0F", subtitle: "Sin restricciones" },
  { key: "vegana", label: "Vegana", emoji: "\uD83C\uDF31", subtitle: "Sin productos animales" },
  { key: "vegetariana", label: "Vegetariana", emoji: "\uD83E\uDD5A", subtitle: "Sin carne ni pescado" },
  { key: "sin_gluten", label: "Sin gluten", emoji: "\uD83C\uDF3E", subtitle: "Apta para celiacos" },
  { key: "low_fodmap", label: "Low FODMAP", emoji: "\uD83E\uDED0", subtitle: "Para intestino sensible" },
  { key: "sin_picos_glucosa", label: "Control glucosa", emoji: "\uD83D\uDCC9", subtitle: "Indice glucémico bajo" },
  { key: "antiinflamatoria", label: "Antiinflamatoria", emoji: "\uD83D\uDC9A", subtitle: "Reduce inflamación" },
];

export const DIET_FOODS = {
  vegana: {
    menstrual: [
      { name: "Lentejas con limon", reason: "Excelente fuente de hierro vegetal. El limon aporta vitamina C que triplica la absorción del hierro no hemo." },
      { name: "Espinacas salteadas", reason: "Ricas en hierro, magnesio y folato. El magnesio ayuda a reducir los calambres menstruales." },
      { name: "Semillas de calabaza", reason: "Altas en hierro, magnesio y zinc. Una porcion cubre el 40% del magnesio diario necesario." },
      { name: "Chocolate oscuro 85%", reason: "Rico en magnesio y hierro. Estimula la producción de serotonina, mejorando el animo durante la menstruación." },
      { name: "Tofu firme", reason: "Proteina completa con hierro y calcio. Contiene isoflavonas que pueden modular el dolor menstrual." },
      { name: "Quinoa", reason: "Pseudocereal con proteina completa, hierro y magnesio. Sustituye granos refinados sin sacrificar nutrientes." },
      { name: "Semillas de chia con naranja", reason: "Omega-3 antiinflamatorio (ALA) combinado con vitamina C. Ayuda a reducir la inflamación y el dolor." },
      { name: "Kale o col rizada", reason: "Rica en calcio vegetal, hierro y vitamina K. El calcio contribuye a reducir los calambres uterinos." },
    ],
    folicular: [
      { name: "Brocoli al vapor", reason: "Crucifero rico en sulforafano que apoya al hígado en el metabolismo del estrogeno en ascenso." },
      { name: "Garbanzos", reason: "Proteina vegetal con fibra y B6. La fibra ayuda a eliminar el exceso de estrogeno via digestiva." },
      { name: "Linaza molida", reason: "Contiene lignanos que modulan el estrogeno naturalmente. Rica en omega-3 y fibra soluble." },
      { name: "Aguacate", reason: "Grasas monoinsaturadas que apoyan la producción hormonal. Rico en folato, potasio y vitamina E." },
      { name: "Nueces", reason: "Omega-3 vegetal y antioxidantes. Mejoran la función cognitiva, que esta en ascenso con el estrogeno." },
      { name: "Edamame", reason: "Proteina completa con fibra e isoflavonas. Apoya el equilibrio estrogenico de forma natural." },
      { name: "Camote o boniato", reason: "Carbohidrato complejo rico en betacaroteno y fibra. Proporciona energia sostenida para esta fase activa." },
      { name: "Espinaca con semillas de girasol", reason: "Combinacion rica en folato, vitamina E y hierro. Prepara el cuerpo para la fase ovulatoria." },
    ],
    ovulatoria: [
      { name: "Coliflor", reason: "Crucifero que contiene indol-3-carbinol, esencial para metabolizar el pico de estrogeno de la ovulacion." },
      { name: "Coles de Bruselas", reason: "Ricas en vitamina C, fibra y glucosinolatos que apoyan la desintoxicacion del exceso de estrogeno." },
      { name: "Pimiento rojo", reason: "Contiene el doble de vitamina C que la naranja. Antioxidante potente en el momento de mayor estres oxidativo." },
      { name: "Tempeh", reason: "Proteina fermentada de soja con probioticos naturales. Apoya la salud intestinal y el metabolismo hormonal." },
      { name: "Esparragos", reason: "Ricos en folato (B9) y glutathion, un antioxidante maestro. Esenciales durante el pico de fertilidad." },
      { name: "Arandanos", reason: "Potente fuente de antocianinas antioxidantes. Protegen las celulas del estres oxidativo del pico hormonal." },
      { name: "Semillas de hemp", reason: "Proteina completa con omega-3 y omega-6 en proporcion ideal. Apoyan la función reproductiva." },
      { name: "Repollo morado", reason: "Crucifero rico en antocianinas y vitamina C. Doble función: metabolizar estrogeno y proteger celulas." },
    ],
    lutea: [
      { name: "Platano", reason: "Rico en vitamina B6 y triptofano que elevan la serotonina. Combate los cambios de humor premenstruales." },
      { name: "Avena", reason: "Carbohidrato complejo que eleva la serotonina de forma sostenida. Rica en magnesio y fibra para reducir PMS." },
      { name: "Almendras", reason: "Altas en magnesio, calcio y vitamina E. El magnesio reduce los sintomas de PMS hasta un 35%." },
      { name: "Garbanzos tostados", reason: "Ricos en B6, magnesio y zinc. El zinc apoya la producción de progesterona en esta fase." },
      { name: "Camote asado", reason: "Carbohidrato complejo de IG moderado. Satisface antojos de forma saludable y estabiliza el azucar." },
      { name: "Tahini (pasta de sesamo)", reason: "Excelente fuente de calcio vegetal, magnesio y zinc. El calcio reduce significativamente el PMS." },
      { name: "Kale salteada con limon", reason: "Calcio vegetal altamente absorbible, magnesio y vitamina K. Trio esencial contra los sintomas premenstruales." },
      { name: "Semillas de girasol", reason: "Ricas en vitamina E, magnesio y selenio. La vitamina E reduce el dolor mamario premenstrual." },
    ],
  },

  vegetariana: {
    menstrual: [
      { name: "Huevos revueltos con espinaca", reason: "Proteina completa con hierro hemo y no hemo. La espinaca aporta magnesio para reducir calambres." },
      { name: "Yogurt griego con semillas de calabaza", reason: "Calcio y probioticos del yogurt con hierro y magnesio de las semillas. Combinacion anti-calambres." },
      { name: "Lentejas guisadas", reason: "Alta en hierro vegetal y proteina. Combinada con vitamina C, reemplaza eficazmente las reservas de hierro perdidas." },
      { name: "Queso panela o cottage", reason: "Proteina de alta calidad con calcio y B12. El calcio ayuda a reducir los espasmos musculares uterinos." },
      { name: "Chocolate oscuro 70%", reason: "Magnesio y hierro en cada onza. Libera endorfinas que alivian el dolor y mejoran el animo." },
      { name: "Quinoa con verduras", reason: "Proteina completa con hierro y magnesio. Carbohidrato complejo que mantiene energia estable durante la menstruación." },
      { name: "Espinacas con limon", reason: "Hierro vegetal potenciado por la vitamina C del limon. Folato y magnesio para el bienestar menstrual." },
      { name: "Semillas de chia en yogurt", reason: "Omega-3 antiinflamatorio con calcio y probioticos. Reduce la inflamación y apoya la salud digestiva." },
    ],
    folicular: [
      { name: "Huevo cocido", reason: "Colina esencial para el metabolismo del estrogeno y la función cerebral. Proteina completa con B12." },
      { name: "Brocoli gratinado con queso", reason: "Sulforafano del brocoli para metabolizar estrogeno, calcio del queso para salud osea en fase de construccion." },
      { name: "Linaza molida en yogurt", reason: "Lignanos que modulan el estrogeno combinados con probioticos. Apoyan el equilibrio hormonal digestivo." },
      { name: "Aguacate", reason: "Grasas saludables esenciales para la producción hormonal. Rico en folato, potasio y vitamina E." },
      { name: "Garbanzos", reason: "Fibra y proteina vegetal que ayudan a eliminar el exceso de estrogeno. Ricos en folato y B6." },
      { name: "Nueces y almendras", reason: "Omega-3 y vitamina E que apoyan la función cognitiva en ascenso. Antioxidantes para proteccion celular." },
      { name: "Camote", reason: "Betacaroteno que el cuerpo convierte en vitamina A, esencial para la salud reproductiva. Fibra y energia." },
      { name: "Ensalada de espinaca con huevo", reason: "Hierro y folato de la espinaca con proteina completa del huevo. Prepara el cuerpo para la ovulacion." },
    ],
    ovulatoria: [
      { name: "Omelette de verduras", reason: "Proteina completa con colina del huevo. Las verduras aportan antioxidantes para el pico hormonal." },
      { name: "Coliflor y brocoli", reason: "Cruciferos ricos en indol-3-carbinol para metabolizar el pico de estrogeno de forma eficiente." },
      { name: "Yogurt con arandanos", reason: "Probioticos que apoyan el metabolismo hormonal con antioxidantes que protegen del estres oxidativo." },
      { name: "Esparragos", reason: "La fuente vegetal mas rica en folato. Contiene glutathion antioxidante, clave en el pico de fertilidad." },
      { name: "Pimiento rojo y zanahoria", reason: "Vitamina C y betacaroteno antioxidantes. Protegen las celulas reproductivas del estres oxidativo." },
      { name: "Queso fresco con nueces", reason: "Calcio y B12 del queso con omega-3 de las nueces. Apoyan la función reproductiva y cerebral." },
      { name: "Repollo morado", reason: "Antocianinas antioxidantes con glucosinolatos para metabolizar estrogeno. Doble proteccion celular." },
      { name: "Semillas de hemp", reason: "Proteina completa con omega-3 y omega-6 en proporcion ideal 3:1. Apoyan la ovulacion saludable." },
    ],
    lutea: [
      { name: "Yogurt griego con platano", reason: "Triptofano y B6 del platano elevan la serotonina. Calcio y proteina del yogurt reducen el PMS." },
      { name: "Avena con almendras", reason: "Carbohidrato complejo que eleva serotonina con magnesio de las almendras contra el PMS." },
      { name: "Huevos con camote", reason: "B6 del huevo apoya el metabolismo de progesterona. Camote satisface antojos con IG moderado." },
      { name: "Queso cottage con semillas de girasol", reason: "Calcio y proteina con vitamina E y selenio. Reducen dolor mamario y sintomas premenstruales." },
      { name: "Chocolate oscuro 70%", reason: "Magnesio que reduce PMS hasta 35%. Estimula serotonina y endorfinas contra cambios de humor." },
      { name: "Garbanzos con espinaca", reason: "B6, zinc y magnesio de los garbanzos con calcio y hierro de la espinaca. Combo anti-PMS completo." },
      { name: "Leche dorada (leche + curcuma)", reason: "Calcio de la leche con efecto antiinflamatorio de la curcuma. Reconfortante y terapéutico." },
      { name: "Nueces de Brasil", reason: "La fuente mas concentrada de selenio. Solo 2-3 cubren el requerimiento diario, esencial para la tiroides." },
    ],
  },

  sin_gluten: {
    menstrual: [
      { name: "Quinoa con espinacas", reason: "Pseudocereal sin gluten con proteina completa. Hierro y magnesio de la espinaca para reducir calambres." },
      { name: "Salmon a la plancha", reason: "Omega-3 EPA y DHA con accion antiinflamatoria directa. Reduce el dolor menstrual y la inflamación." },
      { name: "Arroz integral con lentejas", reason: "Combinacion sin gluten que forma proteina completa. Hierro vegetal y fibra para sostener energia." },
      { name: "Semillas de calabaza", reason: "Naturalmente sin gluten, ricas en hierro, magnesio y zinc. Snack perfecto durante la menstruación." },
      { name: "Chocolate oscuro (verificar sin gluten)", reason: "Magnesio y hierro. Busca etiqueta certificada sin gluten para evitar contaminacion cruzada." },
      { name: "Papas al horno con romero", reason: "Carbohidrato sin gluten rico en potasio y vitamina C. El romero tiene propiedades antiinflamatorias." },
      { name: "Huevos con verduras", reason: "Proteina completa naturalmente sin gluten. Con verduras de hoja verde aportan hierro y folato." },
      { name: "Amaranto cocido", reason: "Grano ancestral sin gluten con mas hierro que la espinaca. Rico en calcio, magnesio y proteina." },
    ],
    folicular: [
      { name: "Brocoli y coliflor al vapor", reason: "Cruciferos sin gluten que apoyan el metabolismo del estrogeno en ascenso. Ricos en sulforafano." },
      { name: "Trigo sarraceno (no es trigo)", reason: "A pesar de su nombre, no contiene gluten. Rico en rutina antioxidante, magnesio y proteina." },
      { name: "Mijo con verduras", reason: "Cereal sin gluten rico en magnesio y vitaminas B. Alternativa nutritiva y versatil." },
      { name: "Aguacate", reason: "Naturalmente sin gluten, rico en grasas saludables para la producción hormonal y folato." },
      { name: "Linaza molida", reason: "Lignanos moduladores de estrogeno, omega-3 y fibra. Naturalmente libre de gluten." },
      { name: "Garbanzos", reason: "Legumbre sin gluten rica en fibra y proteina. La fibra ayuda a regular el estrogeno en ascenso." },
      { name: "Nueces y almendras", reason: "Omega-3 y vitamina E sin gluten. Apoyan la función cognitiva mejorada de esta fase." },
      { name: "Camote asado", reason: "Tubérculo sin gluten rico en betacaroteno y fibra. Energia sostenida para la fase mas activa." },
    ],
    ovulatoria: [
      { name: "Coles de Bruselas asadas", reason: "Crucifero sin gluten con glucosinolatos para metabolizar el pico de estrogeno eficientemente." },
      { name: "Quinoa con esparragos", reason: "Proteina completa sin gluten con folato. Combinacion ideal para el pico de fertilidad." },
      { name: "Pimientos de colores", reason: "Vitamina C y antioxidantes sin gluten. Protegen celulas del estres oxidativo del pico hormonal." },
      { name: "Salmon o sardinas", reason: "Omega-3, vitamina D y proteina sin gluten. Apoyan la función reproductiva en la ovulacion." },
      { name: "Arandanos y fresas", reason: "Antocianinas antioxidantes naturalmente sin gluten. Proteccion celular durante el pico hormonal." },
      { name: "Arroz integral con vegetales", reason: "Base sin gluten con fibra y minerales. Energia sostenida sin inflamación intestinal." },
      { name: "Repollo morado rallado", reason: "Crucifero con antocianinas, vitamina C y sin gluten. Metaboliza estrogeno y protege celulas." },
      { name: "Huevos con espinaca", reason: "Colina para metabolismo hormonal, folato y hierro. Todo naturalmente libre de gluten." },
    ],
    lutea: [
      { name: "Avena certificada sin gluten", reason: "Avena pura sin contaminacion. Eleva serotonina con carbohidratos complejos, rica en magnesio contra PMS." },
      { name: "Platano con almendras", reason: "Triptofano y B6 del platano con magnesio de almendras. Combinacion anti-PMS naturalmente sin gluten." },
      { name: "Papas con salmon", reason: "Carbohidrato sin gluten con omega-3 antiinflamatorio. Satisface antojos de forma saludable." },
      { name: "Arroz con garbanzos", reason: "Proteina completa sin gluten con B6, magnesio y zinc. Apoya la producción de progesterona." },
      { name: "Chocolate oscuro certificado SG", reason: "Magnesio contra PMS. Elegir marcas certificadas sin gluten para seguridad celiaca." },
      { name: "Camote con canela", reason: "IG moderado sin gluten. La canela estabiliza el azucar y el camote satisface antojos de carbohidratos." },
      { name: "Semillas de girasol y calabaza", reason: "Vitamina E, magnesio, zinc y selenio sin gluten. Reducen dolor mamario y sintomas premenstruales." },
      { name: "Yogurt con nueces de Brasil", reason: "Calcio y probioticos con selenio. Apoyan tiroides y reducen retencion de liquidos." },
    ],
  },

  low_fodmap: {
    menstrual: [
      { name: "Espinaca salteada con jengibre", reason: "Baja en FODMAPs, rica en hierro y magnesio. El jengibre reduce calambres sin irritar el intestino." },
      { name: "Huevos cocidos", reason: "Proteina completa baja en FODMAPs. Faciles de digerir durante la menstruación cuando el intestino es mas sensible." },
      { name: "Zanahoria y papa al horno", reason: "Vegetales bajos en FODMAPs ricos en potasio y vitamina A. Reconfortantes sin causar hinchazón." },
      { name: "Salmon a la plancha", reason: "Omega-3 antiinflamatorio, proteina completa y sin FODMAPs. Reduce dolor menstrual e inflamación intestinal." },
      { name: "Arandanos (porcion 40g)", reason: "Fruta baja en FODMAPs rica en antioxidantes. En porcion controlada no causa sintomas digestivos." },
      { name: "Arroz blanco con pollo", reason: "Combinacion basica low FODMAP facil de digerir. Aporta energia y proteina sin irritar el intestino." },
      { name: "Tofu firme (no sedoso)", reason: "Proteina vegetal baja en FODMAPs (el firme pierde los galactanos). Hierro y calcio sin molestias." },
      { name: "Kiwi", reason: "Bajo en FODMAPs, rico en vitamina C y actinidina que mejora la digestion. Ayuda con el estrenimiento." },
    ],
    folicular: [
      { name: "Brocoli (3/4 taza maximo)", reason: "Bajo en FODMAPs en porcion controlada. Sulforafano para metabolizar el estrogeno en ascenso." },
      { name: "Avena (1/2 taza)", reason: "Baja en FODMAPs en porcion pequena. Fibra soluble que alimenta bacterias buenas sin causar gas." },
      { name: "Pimiento rojo y zanahoria", reason: "Vegetales bajos en FODMAPs ricos en vitamina C y betacaroteno. Antioxidantes sin irritacion." },
      { name: "Huevos con espinaca", reason: "Proteina y folato bajos en FODMAPs. Apoyan la energia creciente de esta fase sin sintomas." },
      { name: "Nueces (10 unidades)", reason: "Bajas en FODMAPs en porcion controlada. Omega-3 y vitamina E para función cognitiva." },
      { name: "Quinoa", reason: "Pseudocereal bajo en FODMAPs, proteina completa. Alternativa segura al trigo para intestino sensible." },
      { name: "Fresas (5 unidades)", reason: "Bajas en FODMAPs con vitamina C y antioxidantes. Dulzura natural sin fructosa excesiva." },
      { name: "Pollo o pavo", reason: "Proteinas magras sin FODMAPs. Con especias suaves aportan energia para esta fase activa." },
    ],
    ovulatoria: [
      { name: "Pepino y tomate cherry", reason: "Vegetales bajos en FODMAPs, hidratantes y ricos en licopeno antioxidante. Ligeros y refrescantes." },
      { name: "Salmon con limon", reason: "Omega-3 y vitamina D sin FODMAPs. Apoya la función reproductiva en el pico de fertilidad." },
      { name: "Espinaca con semillas de calabaza", reason: "Folato y hierro bajos en FODMAPs. Las semillas aportan zinc para la fase ovulatoria." },
      { name: "Arroz integral (1 taza)", reason: "Bajo en FODMAPs, fibra y minerales. Energia sostenida sin irritacion digestiva." },
      { name: "Naranja", reason: "Baja en FODMAPs, rica en vitamina C y folato. Apoya la absorción de hierro y la inmunidad." },
      { name: "Pimientos asados", reason: "Bajos en FODMAPs con vitamina C antioxidante. Protegen celulas durante el pico hormonal." },
      { name: "Tofu firme con verduras", reason: "Proteina low FODMAP con vegetales seguros. Combinacion completa sin sintomas digestivos." },
      { name: "Arandanos con nueces", reason: "Antioxidantes y omega-3 bajos en FODMAPs en porciones controladas. Snack hormonal ideal." },
    ],
    lutea: [
      { name: "Avena con platano (firme)", reason: "Carbohidrato complejo para serotonina. Platano firme es bajo en FODMAPs (el maduro no)." },
      { name: "Chocolate oscuro (20g)", reason: "Magnesio contra PMS en porcion low FODMAP. Porcion pequena evita exceso de fructanos del cacao." },
      { name: "Papa al horno con mantequilla", reason: "Carbohidrato satisfactorio bajo en FODMAPs. La mantequilla es baja en lactosa en pequenas cantidades." },
      { name: "Almendras (10 unidades)", reason: "Magnesio y calcio en porcion low FODMAP controlada. Reduce sintomas premenstruales." },
      { name: "Arroz con pollo y zanahoria", reason: "Comida completa 100% low FODMAP. Proteina, carbohidrato y vegetales sin irritacion." },
      { name: "Semillas de calabaza", reason: "Bajas en FODMAPs con magnesio, zinc y hierro. Snack anti-PMS que no inflama el intestino." },
      { name: "Kiwi", reason: "Bajo en FODMAPs, vitamina C y fibra suave. Mejora el transito lento comun en fase lutea." },
      { name: "Huevos revueltos con espinaca", reason: "Proteina facil con folato y hierro, todo bajo en FODMAPs. Ideal cuando el intestino esta sensible." },
    ],
  },

  sin_picos_glucosa: {
    menstrual: [
      { name: "Lentejas con verduras", reason: "Indice glucémico de 29 (muy bajo). Hierro y proteina vegetal que mantienen glucosa estable durante la menstruación." },
      { name: "Huevos con aguacate", reason: "Proteina y grasas saludables sin carbohidratos. Mantienen glucosa plana mientras aportan energia y saciedad." },
      { name: "Salmon con espinacas", reason: "Proteina con omega-3 antiinflamatorio, sin impacto glucémico. El hierro de la espinaca sin picos de azucar." },
      { name: "Nueces y almendras", reason: "IG de 15, ricas en magnesio y grasas saludables. Snack que no eleva la glucosa y reduce calambres." },
      { name: "Quinoa con limon", reason: "IG de 53 (medio-bajo), proteina completa. Mucho mejor que el arroz blanco para estabilidad glucemica." },
      { name: "Yogurt griego sin azucar", reason: "Proteina alta con IG bajo de 11. El calcio reduce calambres sin causar picos de glucosa." },
      { name: "Garbanzos tostados", reason: "IG de 28, ricos en hierro y fibra. La fibra ralentiza la absorción de azucar drasticamente." },
      { name: "Chocolate oscuro 85%+ (20g)", reason: "IG de 23. Magnesio y hierro con minimo impacto glucémico. Satisface antojos sin picos." },
    ],
    folicular: [
      { name: "Brocoli con huevo", reason: "Crucifero de IG 10 con proteina. Metaboliza estrogeno sin ningun impacto en la glucosa." },
      { name: "Avena steel-cut con nueces", reason: "IG de 42 (vs 79 de avena instantanea). Las nueces y grasas bajan aun mas la respuesta glucemica." },
      { name: "Aguacate con semillas", reason: "Grasas monoinsaturadas que mejoran la sensibilidad a la insulina. IG practicamente nulo." },
      { name: "Lentejas o frijoles negros", reason: "IG bajo de 29-30. La fibra soluble crea un gel que ralentiza la absorción de glucosa." },
      { name: "Linaza molida", reason: "IG de 0, rica en omega-3 y lignanos. Modula estrogeno sin afectar la glucosa en absoluto." },
      { name: "Ensalada de hojas verdes con proteina", reason: "Vegetales de hoja tienen IG cercano a 0. Combinados con proteina mantienen glucosa perfectamente estable." },
      { name: "Camote al horno (con piel)", reason: "IG de 44 con piel (vs 94 en pure). La fibra de la piel y enfriarlo baja el indice glucémico." },
      { name: "Tofu salteado con verduras", reason: "Proteina de IG bajo con vegetales. Combinacion que mantiene energia sin picos de insulina." },
    ],
    ovulatoria: [
      { name: "Coliflor como base", reason: "IG de 15. Sustituye arroz o pasta como base crucifero. Metaboliza estrogeno sin elevar glucosa." },
      { name: "Salmon con esparragos", reason: "Cero impacto glucémico. Omega-3 y folato para apoyar la ovulacion con glucosa plana." },
      { name: "Arandanos con yogurt griego", reason: "Arandanos tienen IG de 53 pero la proteina del yogurt baja la respuesta glucemica total a ~25." },
      { name: "Ensalada de col con vinagre", reason: "Crucifero de IG bajo. El vinagre reduce la respuesta glucemica de toda la comida hasta un 30%." },
      { name: "Huevos con pimientos", reason: "IG cercano a 0. Colina del huevo y vitamina C del pimiento sin impacto en la glucosa." },
      { name: "Garbanzos con espinaca", reason: "IG de 28. Folato y hierro para el pico de fertilidad con glucosa completamente estable." },
      { name: "Nueces de macadamia", reason: "IG de 10, las mas ricas en grasas monoinsaturadas. Mejoran sensibilidad a insulina." },
      { name: "Semillas de hemp", reason: "IG de 0, proteina completa con omega-3. Apoyan ovulacion sin ningun efecto glucémico." },
    ],
    lutea: [
      { name: "Avena steel-cut con canela y nueces", reason: "IG moderado. La canela reduce glucosa postprandial un 18-29%. Critico en fase lutea cuando hay resistencia a insulina." },
      { name: "Camote al horno (frio)", reason: "El almidon resistente del camote frio baja su IG a 35. Satisface antojos de carbos sin picos glucémicos." },
      { name: "Garbanzos con curcuma", reason: "IG de 28 con antiinflamatorio. La resistencia a insulina aumenta en fase lutea — los garbanzos la contrarrestan." },
      { name: "Almendras y chocolate 85%", reason: "IG combinado de ~15. Magnesio contra PMS con minimo impacto glucémico. Snack perfecto premenstrual." },
      { name: "Lentejas con arroz integral", reason: "IG combinado de ~35. Proteina completa que eleva serotonina sin los picos que empeoran el PMS." },
      { name: "Yogurt griego con semillas de chia", reason: "IG de 11 con omega-3. Proteina y grasas que amortiguan cualquier respuesta glucemica." },
      { name: "Ensalada con aguacate y huevo", reason: "IG cercano a 0. Grasas y proteina que mantienen saciedad y glucosa plana en la fase mas vulnerable." },
      { name: "Edamame", reason: "IG de 18 con proteina completa y magnesio. Snack luteo ideal sin impacto glucémico." },
    ],
  },

  antiinflamatoria: {
    menstrual: [
      { name: "Salmon silvestre", reason: "Rico en omega-3 EPA/DHA con accion antiinflamatoria directa. Reduce prostaglandinas que causan dolor menstrual." },
      { name: "Jengibre fresco (te o rallado)", reason: "Tan efectivo como el ibuprofeno para dolor menstrual segun estudios. Inhibe la producción de prostaglandinas." },
      { name: "Curcuma con pimienta negra", reason: "La curcumina es antiinflamatoria potente. La pimienta negra aumenta su absorción un 2000%." },
      { name: "Arandanos y frambuesas", reason: "Antocianinas que reducen marcadores inflamatorios (IL-6, TNF-alfa). Proteccion celular durante la menstruación." },
      { name: "Espinacas", reason: "Ricas en hierro y antioxidantes antiinflamatorios. El magnesio relaja musculos reduciendo calambres." },
      { name: "Nueces", reason: "Mejor ratio omega-3/omega-6 entre los frutos secos. Reducen inflamación sistemica y dolor menstrual." },
      { name: "Aceite de oliva extra virgen", reason: "Contiene oleocanthal con efecto similar al ibuprofeno. 3 cucharadas equivalen a ~10% de una dosis." },
      { name: "Semillas de chia", reason: "La fuente vegetal mas concentrada de omega-3 (ALA). Antiinflamatorio que reduce dolor y hinchazon." },
    ],
    folicular: [
      { name: "Brocoli", reason: "Sulforafano antiinflamatorio que tambien metaboliza el estrogeno en ascenso. Doble beneficio en esta fase." },
      { name: "Te verde matcha", reason: "EGCG es un polifenol antiinflamatorio potente. Tambien mejora la concentracion sin los picos de cafe." },
      { name: "Aguacate", reason: "Grasas monoinsaturadas antiinflamatorias. Reduce marcadores inflamatorios y apoya producción hormonal." },
      { name: "Sardinas o caballa", reason: "Omega-3 EPA/DHA concentrado. Peces pequenos con menos mercurio y mas beneficio antiinflamatorio." },
      { name: "Linaza molida", reason: "Omega-3 vegetal con lignanos antiinflamatorios. Modula estrogeno y reduce inflamación simultaneamente." },
      { name: "Espinaca con aceite de oliva", reason: "Hierro con oleocanthal antiinflamatorio. El aceite mejora absorción de vitaminas liposolubles." },
      { name: "Bayas de goji o acai", reason: "Superalimentos con ORAC (capacidad antioxidante) extremadamente alto. Reducen estres oxidativo." },
      { name: "Cebolla morada (cruda)", reason: "Rica en quercetina, un antiinflamatorio natural que estabiliza mastocitos y reduce histamina." },
    ],
    ovulatoria: [
      { name: "Coles de Bruselas con aceite de oliva", reason: "Glucosinolatos antiinflamatorios que metabolizan estrogeno. El aceite aporta oleocanthal adicional." },
      { name: "Salmon con curcuma", reason: "Omega-3 con curcumina: combinacion antiinflamatoria sinergica. Protege celulas en el pico hormonal." },
      { name: "Arandanos y granada", reason: "Antocianinas y punicalaginas: dos de los antioxidantes antiinflamatorios mas potentes conocidos." },
      { name: "Esparragos", reason: "Ricos en glutathion, el antioxidante maestro del cuerpo. Saponinas con propiedades antiinflamatorias." },
      { name: "Tomates cocidos", reason: "El licopeno aumenta 5x con la coccion. Poderoso antiinflamatorio que protege durante la ovulacion." },
      { name: "Nueces y semillas de hemp", reason: "Omega-3 vegetal en proporcion antiinflamatoria ideal. Apoyan la ovulacion reduciendo inflamación." },
      { name: "Repollo fermentado (chucrut)", reason: "Probioticos que reducen inflamación intestinal. El 70% del sistema inmune esta en el intestino." },
      { name: "Pimiento rojo", reason: "Vitamina C antioxidante que reduce marcadores inflamatorios. Mas vitamina C que cualquier citrico." },
    ],
    lutea: [
      { name: "Curcuma latte (leche dorada)", reason: "Curcumina antiinflamatoria con leche que aporta calcio contra PMS. Bebida reconfortante y terapeutica." },
      { name: "Chocolate oscuro 85%", reason: "Flavonoides antiinflamatorios con magnesio. Reduce PMS y satisface antojos sin promover inflamación." },
      { name: "Salmon o atun", reason: "Omega-3 que contrarresta las prostaglandinas inflamatorias premenstruales. Reduce dolor e hinchazon." },
      { name: "Jengibre y canela (te)", reason: "Jengibre antiinflamatorio con canela que estabiliza glucosa. Combinacion perfecta para la fase premenstrual." },
      { name: "Almendras y nueces", reason: "Magnesio, vitamina E y omega-3 antiinflamatorios. Reducen marcadores de inflamación y sintomas PMS." },
      { name: "Espinaca con aceite de oliva y limon", reason: "Trio antiinflamatorio: hierro + oleocanthal + vitamina C. Combate inflamación premenstrual." },
      { name: "Camote asado con romero", reason: "Betacaroteno con acido rosmarínico del romero (antiinflamatorio). Satisface antojos sin inflamar." },
      { name: "Semillas de calabaza", reason: "Zinc y magnesio antiinflamatorios. El zinc modula la respuesta inmune y reduce la inflamación lutea." },
    ],
  },
};

export function getFoodsForDiet(phaseName, dietType) {
  if (!dietType || dietType === "general") return null;
  return DIET_FOODS[dietType]?.[phaseName] || null;
}
