/**
 * Alimentos regionales por fase del ciclo menstrual.
 * Cada region tiene 8 alimentos por fase, especificos de la zona
 * y con razones cientificas adaptadas.
 */

export const REGIONS = [
  { key: "general", label: "General", emoji: "\uD83C\uDF0E", subtitle: "Alimentos universales" },
  { key: "mexico", label: "Mexico", emoji: "\uD83C\uDDF2\uD83C\uDDFD", subtitle: "Nopales, amaranto, guayaba..." },
  { key: "colombia", label: "Colombia", emoji: "\uD83C\uDDE8\uD83C\uDDF4", subtitle: "Platano, lulo, uchuva..." },
  { key: "argentina", label: "Argentina", emoji: "\uD83C\uDDE6\uD83C\uDDF7", subtitle: "Yerba mate, lentejas, quinoa..." },
  { key: "peru", label: "Peru", emoji: "\uD83C\uDDF5\uD83C\uDDEA", subtitle: "Quinoa, maca, camu camu..." },
  { key: "chile", label: "Chile", emoji: "\uD83C\uDDE8\uD83C\uDDF1", subtitle: "Cochayuyo, porotos, murta..." },
  { key: "centroamerica", label: "Centroamerica", emoji: "\uD83C\uDF34", subtitle: "Frijoles, chayote, loroco..." },
  { key: "espana", label: "Espana", emoji: "\uD83C\uDDEA\uD83C\uDDF8", subtitle: "Aceite de oliva, garbanzos..." },
];

export const REGIONAL_FOODS = {
  mexico: {
    menstrual: [
      { name: "Nopales con chile guajillo", reason: "Altos en hierro y calcio. Los capsaicinoides del chile liberan endorfinas que alivian calambres menstruales." },
      { name: "Mole con cacao", reason: "El cacao aporta 64mg de magnesio por onza, estimulando serotonina. Las especias del mole tienen propiedades antiinflamatorias." },
      { name: "Amaranto (alegria)", reason: "Pseudocereal con mas hierro que la espinaca (7.6mg/100g). Lisina esencial para la absorcion de calcio y recuperacion." },
      { name: "Atole de avena", reason: "Carbohidratos complejos que elevan serotonina via triptofano. Bebida caliente que relaja la musculatura uterina." },
      { name: "Quelites (verdolagas, quintoniles)", reason: "Hierba silvestre mexicana rica en hierro, magnesio y omega-3. Repone minerales perdidos durante el sangrado." },
      { name: "Guayaba", reason: "Contiene 4x mas vitamina C que la naranja, aumentando drasticamente la absorcion de hierro no-hemo de otros alimentos." },
      { name: "Frijoles negros con epazote", reason: "Hierro vegetal y vitaminas B. El epazote reduce gases y mejora la digestion, comun problema durante la menstruacion." },
      { name: "Pepitas de calabaza (pepitoria)", reason: "156mg de magnesio por porcion, uno de los alimentos mas altos. Reduce calambres y mejora el sueno menstrual." },
    ],
    folicular: [
      { name: "Chayote y calabacita", reason: "Ricos en folato y zinc que apoyan la sintesis de FSH y LH para el desarrollo saludable del foliculo." },
      { name: "Jicama", reason: "Prebiotico natural (inulina) que alimenta el estroboloma, el microbioma que metaboliza el estrogeno en ascenso." },
      { name: "Pepitas de calabaza tostadas", reason: "Zinc critico para la sintesis de FSH y LH. Las pepitas mexicanas son de las fuentes mas ricas (7.6mg/100g)." },
      { name: "Pollo en salsa verde", reason: "Proteina magra para la sintesis muscular favorecida por el estrogeno. El tomatillo aporta vitamina C y antioxidantes." },
      { name: "Tortilla de maiz nixtamalizado", reason: "El proceso de nixtamalizacion libera niacina (B3) y aumenta la biodisponibilidad de calcio. Energia sostenida." },
      { name: "Aguacate (en todo)", reason: "Grasas monoinsaturadas esenciales para produccion hormonal. Mexico es el mayor productor mundial, siempre fresco." },
      { name: "Tejocote o tunas", reason: "Antioxidantes y vitamina C que protegen los foliculos en desarrollo. Fibra soluble para balance de azucar." },
      { name: "Esquites con limon", reason: "El maiz aporta fibra y vitaminas B. El limon mejora la absorcion de hierro. El elote fresco tiene mas nutrientes." },
    ],
    ovulatoria: [
      { name: "Brocoli al vapor con limon", reason: "I3C y DIM para metabolizar el pico maximo de estrogeno. Disponible todo el ano en mercados mexicanos." },
      { name: "Huevos rancheros", reason: "Proteina completa con colina para integridad celular. El jitomate y chile aportan licopeno y capsaicina antioxidante." },
      { name: "Nopal asado con queso panela", reason: "El nopal regula glucosa y aporta fibra. El queso panela da calcio y proteina sin exceso de grasa." },
      { name: "Ensalada de berros y pepita", reason: "Berros son cruciferas con DIM para procesar estrogeno. Vitamina E de pepitas protege funcion ovarica." },
      { name: "Sardinas en tomate", reason: "Omega-3, vitamina D y calcio (de las espinas). Economicas y accesibles en todo Mexico." },
      { name: "Elote hervido", reason: "Folato (B9) para division celular durante la ovulacion. Fibra que ayuda al higado a procesar estrogeno." },
      { name: "Flor de calabaza", reason: "Rica en folato y vitamina A. Delicadeza mexicana que apoya la funcion reproductiva con minerales esenciales." },
      { name: "Papaya con limon", reason: "Enzimas digestivas (papaina) y vitamina C. Los carotenoides protegen celulas reproductivas del estres oxidativo." },
    ],
    lutea: [
      { name: "Chocolate mexicano con canela", reason: "Magnesio del cacao reduce PMS en 33%. La canela estabiliza azucar en sangre durante los antojos luteos." },
      { name: "Camote morado al horno", reason: "Carbohidratos complejos que elevan serotonina via triptofano. Antocianos del camote morado son antiinflamatorios." },
      { name: "Pozole rojo", reason: "Maiz (hominy) aporta triptofano para serotonina. El caldo caliente reconforta. Carne magra da B6 para progesterona." },
      { name: "Avena con platano y canela", reason: "Metabolismo sube ~300 cal/dia en esta fase. Los carbohidratos complejos dan combustible real sin picos de azucar." },
      { name: "Tlacoyos de frijol", reason: "Vitamina B6 de frijoles apoya progesterona. La masa nixtamalizada aporta calcio. Fibra contrarresta estrenimiento." },
      { name: "Licuado de mamey", reason: "Rico en potasio que reduce retencion de liquidos. Vitaminas A y C. Cremoso y satisfactorio para antojos." },
      { name: "Chiles rellenos de queso", reason: "Capsaicina libera endorfinas. El queso aporta calcio (1000mg/dia reduce PMS). Proteina satisface el hambre." },
      { name: "Agua de jamaica", reason: "Rica en antocianinas antiinflamatorias y vitamina C. Diuretica natural que ayuda con la hinchazon premenstrual." },
    ],
  },

  colombia: {
    menstrual: [
      { name: "Sancocho de gallina", reason: "Caldo rico en minerales del hueso. Proteina y hierro de la gallina. Verduras aportan vitaminas para recuperacion." },
      { name: "Platano maduro asado", reason: "Potasio reduce calambres y vitamina B6 es cofactor de serotonina, que baja con el estrogeno en esta fase." },
      { name: "Lulo (naranjilla)", reason: "Alto en vitamina C (aumenta absorcion de hierro) y hierro natural. Fruta colombiana unica con propiedades antiinflamatorias." },
      { name: "Lentejas guisadas", reason: "6.6mg de hierro por taza. Vitaminas B previenen caidas de azucar que empeoran cambios de humor menstrual." },
      { name: "Aguapanela con limon y jengibre", reason: "El jengibre reduce dolor menstrual con eficacia similar al ibuprofeno. La panela aporta hierro y minerales." },
      { name: "Arepa de maiz con queso", reason: "Carbohidratos reconfortantes. El queso costeño aporta calcio que reduce calambres. Facil de digerir." },
      { name: "Uchuva (physalis)", reason: "Antiinflamatoria natural con vitamina C y hierro. Polifenoles modulan vias inflamatorias NF-kB del dolor menstrual." },
      { name: "Espinaca con hogao", reason: "Hierro y magnesio de la espinaca. El tomate del hogao aporta vitamina C para absorcion de hierro." },
    ],
    folicular: [
      { name: "Ajiaco bogotano", reason: "Tres variedades de papa aportan carbohidratos complejos para energia. Pollo da proteina para sintesis muscular." },
      { name: "Aguacate hass colombiano", reason: "Grasas monoinsaturadas esenciales para produccion hormonal. Colombia es segundo productor mundial, siempre fresco." },
      { name: "Frijoles antioquenos", reason: "Zinc para sintesis de FSH/LH. Fibra alimenta estroboloma. Con platano verde dan energia sostenida." },
      { name: "Guanabana", reason: "Rica en vitamina C y B. Propiedades antiinflamatorias. Fibra que apoya el microbioma en metabolizar estrogeno." },
      { name: "Trucha de rio", reason: "Proteina magra y omega-3 para la ventana anabolica del estrogeno en ascenso. Comun en regiones andinas." },
      { name: "Quinoa colombiana", reason: "Proteina completa con los 9 aminoacidos. Zinc y hierro. Cultivada en los Andes colombianos." },
      { name: "Maracuya (fruta de la pasion)", reason: "Vitamina C y antioxidantes que protegen foliculos. Fibra de las semillas alimenta microbioma intestinal." },
      { name: "Arroz integral con hogao", reason: "Carbohidratos complejos para energia sostenida. El hogao (tomate, cebolla) aporta licopeno y quercetina antioxidante." },
    ],
    ovulatoria: [
      { name: "Bandeja paisa (version ligera)", reason: "Frijoles (B6, B12), huevo (colina), aguacate (grasas), platano (potasio). Plato completo para el pico hormonal." },
      { name: "Brocoli al vapor", reason: "I3C y DIM criticos para metabolizar el pico maximo de estrogeno. Disponible en plazas de mercado." },
      { name: "Huevos pericos", reason: "Proteina completa con colina. El tomate y cebolla aportan licopeno y quercetina para proteccion celular." },
      { name: "Ensalada de palmitos", reason: "Ricos en folato (B9) para division celular durante ovulacion. Fibra y minerales. Producto colombiano." },
      { name: "Bocachico o mojarra", reason: "Pescado de rio con omega-3 y vitamina D. B6 y B12 regulan hormonas en su punto mas alto." },
      { name: "Ensalada de frutas con granola", reason: "Vitaminas C y E protegen celulas reproductivas. Granola aporta selenio para tiroides y balance reproductivo." },
      { name: "Mazorca asada", reason: "Folato para sintesis de ADN. Fibra que ayuda al higado a procesar el pico de estrogeno." },
      { name: "Jugo verde (espinaca, apio, pepino)", reason: "Folato, hierro y vitamina K. Hidratante y alcalinizante. Apoya la desintoxicacion hepatica del estrogeno." },
    ],
    lutea: [
      { name: "Chocolate santandereano", reason: "Cacao colombiano premium con alto magnesio. Reduce PMS en 33%. Tradicion de tomar con queso." },
      { name: "Platano verde cocido", reason: "Almidon resistente que alimenta microbioma. Carbohidrato complejo para el metabolismo aumentado (~300 cal extra)." },
      { name: "Sopa de ahuyama", reason: "Betacarotenos antiinflamatorios. Carbohidratos complejos elevan serotonina via triptofano sin picos de azucar." },
      { name: "Yogurt con mora", reason: "Calcio (1000mg/dia reduce PMS). La mora colombiana es antiinflamatoria y rica en antocianinas." },
      { name: "Almojabanas o pan de bono", reason: "Calcio del queso. Carbohidratos para el metabolismo aumentado. Reconfortante para los antojos de esta fase." },
      { name: "Avena en leche con canela", reason: "Fibra y triptofano para serotonina. La canela estabiliza azucar. Leche aporta calcio anti-PMS." },
      { name: "Garbanzos guisados", reason: "B6 apoya progesterona. Fibra contrarresta estrenimiento por progesterona. Hierro prepara para menstruacion." },
      { name: "Agua de panela con limon", reason: "Minerales (hierro, calcio, magnesio) de la cana. El limon aporta vitamina C. Hidratacion contra retencion." },
    ],
  },

  argentina: {
    menstrual: [
      { name: "Guiso de lentejas", reason: "6.6mg de hierro por taza, plato clasico argentino. Vitaminas B previenen caidas de azucar y cambios de humor." },
      { name: "Mate con limon", reason: "Antioxidantes y minerales del mate. El limon aporta vitamina C que mejora absorcion de hierro no-hemo." },
      { name: "Bife de lomo (corte magro)", reason: "Hierro hemo de alta absorcion (25% vs 5% vegetal). Vitamina B12 y zinc para recuperacion menstrual." },
      { name: "Espinaca a la crema", reason: "Hierro y magnesio de espinaca. La crema aporta calcio. Plato reconfortante que relaja musculatura uterina." },
      { name: "Dulce de membrillo con nueces", reason: "Pectina antiinflamatoria del membrillo. Nueces aportan omega-3 que reduce prostaglandinas del dolor." },
      { name: "Zapallitos rellenos", reason: "Magnesio y potasio del zapallo. Relleno con carne aporta hierro hemo. Facil de digerir durante el periodo." },
      { name: "Naranjas de Tucuman", reason: "Vitamina C (4x mas absorcion de hierro). Argentina produce naranjas de alta calidad en el noroeste." },
      { name: "Chocolate amargo Bariloche", reason: "64mg de magnesio por onza. Serotonina y endorfinas. Tradicion chocolatera patagonica de alta calidad." },
    ],
    folicular: [
      { name: "Ensalada de quinoa andina", reason: "Proteina completa con zinc para FSH/LH. Cultivada en el noroeste argentino. Carbohidratos complejos." },
      { name: "Pollo al verdeo", reason: "Proteina magra para sintesis muscular favorecida por estrogeno. El verdeo aporta folato y vitamina K." },
      { name: "Palta (aguacate) rellena", reason: "Grasas monoinsaturadas para produccion hormonal. La palta mendocina es de las mejores de Sudamerica." },
      { name: "Yogurt con semillas de chia", reason: "Probioticos para estroboloma. Chia argentina (mayor productor) aporta omega-3 y fibra." },
      { name: "Zapallo anco asado", reason: "Betacarotenos y zinc para desarrollo folicular. Fibra alimenta microbioma que metaboliza estrogeno." },
      { name: "Brocoli y coliflor gratinados", reason: "I3C y DIM apoyan metabolismo del estrogeno en ascenso. El queso aporta calcio adicional." },
      { name: "Empanadas de humita", reason: "Maiz aporta fibra y vitaminas B. Energia sostenida para entrenamientos mas intensos de esta fase." },
      { name: "Arandanos patagonicos", reason: "Antioxidantes que protegen foliculos en desarrollo. Argentina produce arandanos premium en la Patagonia." },
    ],
    ovulatoria: [
      { name: "Trucha patagonica", reason: "Omega-3, vitamina D y B12. Regula estrogeno y progesterona en su punto mas alto. Fresca de los lagos." },
      { name: "Ensalada cesar con huevo", reason: "Colina del huevo para membranas celulares. Folato de la lechuga para division celular en ovulacion." },
      { name: "Brocoli salteado con ajo", reason: "I3C y DIM para metabolizar pico de estrogeno. El ajo tiene alicina antiinflamatoria y antioxidante." },
      { name: "Milanesa de soja", reason: "Isoflavonas modulan estrogeno. Proteina vegetal completa. Popular en la cocina argentina vegetariana." },
      { name: "Ensalada de remolacha y zanahoria", reason: "Folato de remolacha para ADN. Betacarotenos de zanahoria protegen celulas reproductivas del estres oxidativo." },
      { name: "Almendras mendocinas", reason: "Vitamina E protege funcion ovarica. Mendoza produce almendras de alta calidad. Selenio para tiroides." },
      { name: "Pan integral con aceite de oliva", reason: "Fibra para procesar estrogeno. Grasas del aceite de oliva apoyan produccion de progesterona post-ovulacion." },
      { name: "Manzanas de Rio Negro", reason: "Quercetina antioxidante. Fibra pectina. Las manzanas del Valle de Rio Negro son de las mejores del mundo." },
    ],
    lutea: [
      { name: "Chocolate patagonico", reason: "Magnesio reduce PMS en 33%. Bariloche tiene tradicion chocolatera con cacao de alta calidad." },
      { name: "Locro (version liviana)", reason: "Zapallo aporta triptofano para serotonina. Maiz y porotos dan energia para metabolismo aumentado." },
      { name: "Bananas de Formosa", reason: "Potasio reduce retencion de agua. B6 apoya serotonina. Argentina produce bananas en el noreste." },
      { name: "Yogurt griego con dulce de leche", reason: "Calcio (1000mg/dia reduce PMS). El dulce de leche satisface antojos de forma controlada." },
      { name: "Semillas de girasol (pipas)", reason: "Argentina es gran productor. Magnesio y vitamina E reducen sensibilidad mamaria e hinchazon." },
      { name: "Avena con manzana y canela", reason: "Triptofano para serotonina. Canela estabiliza azucar. Fibra de la manzana contrarresta estrenimiento." },
      { name: "Garbanzos en guiso", reason: "B6 para progesterona. Fibra contra estrenimiento por progesterona. Hierro prepara para menstruacion." },
      { name: "Mate cocido con leche", reason: "Antioxidantes del mate. Calcio de la leche reduce PMS. Bebida reconfortante para los dias premenstruales." },
    ],
  },

  peru: {
    menstrual: [
      { name: "Quinoa guisada", reason: "Hierro (4.6mg/100g), magnesio y proteina completa. Superalimento peruano ancestral para reponer minerales perdidos." },
      { name: "Camu camu en jugo", reason: "Contiene 60x mas vitamina C que la naranja. Maximiza absorcion de hierro no-hemo durante sangrado menstrual." },
      { name: "Lomo saltado", reason: "Hierro hemo de alta absorcion del lomo. El tomate aporta vitamina C. Cebolla con quercetina antiinflamatoria." },
      { name: "Maca en leche", reason: "Adaptogeno andino que regula el eje hipotalamo-hipofisis-ovario. Reduce fatiga y mejora energia durante el periodo." },
      { name: "Kiwicha (amaranto peruano)", reason: "Mas hierro que la espinaca (7.6mg/100g). Lisina para absorcion de calcio. Grano sagrado de los Incas." },
      { name: "Caldo de gallina", reason: "Tradicion peruana medicinal. Minerales del caldo de hueso. Proteina y hierro para recuperacion menstrual." },
      { name: "Chicha morada", reason: "Maiz morado rico en antocianinas antiinflamatorias. Antioxidante natural que reduce prostaglandinas del dolor." },
      { name: "Platano de la isla", reason: "Potasio reduce calambres. B6 produce serotonina. Variedad peruana dulce y nutritiva." },
    ],
    folicular: [
      { name: "Ceviche de pescado", reason: "Proteina magra y omega-3 para sintesis muscular. El limon maximiza absorcion de hierro y aporta vitamina C." },
      { name: "Aguacate peruano", reason: "Palta fuerte peruana, grasas monoinsaturadas para produccion hormonal. Variedad cremosa y nutritiva." },
      { name: "Habas verdes salteadas", reason: "Zinc para sintesis de FSH/LH. Folato para desarrollo folicular. Proteina vegetal. Comunes en sierra peruana." },
      { name: "Papa nativa (variedades peruanas)", reason: "Peru tiene 3000+ variedades. Carbohidratos complejos para energia. Antioxidantes de las papas de colores." },
      { name: "Lucuma", reason: "Fruta de oro inca con betacarotenos y niacina (B3). Fibra que alimenta estroboloma para metabolizar estrogeno." },
      { name: "Tarwi (chocho)", reason: "Leguminosa andina con 44% proteina. Zinc y hierro. Apoya la ventana anabolica del estrogeno en ascenso." },
      { name: "Olluco salteado", reason: "Tuberculo andino rico en almidones y vitamina C. Energia sostenida para entrenamientos de fase folicular." },
      { name: "Choclo con queso", reason: "Maiz peruano gigante con fibra y vitaminas B. El queso fresco andino aporta calcio y proteina." },
    ],
    ovulatoria: [
      { name: "Trucha del Titicaca", reason: "Omega-3 y vitamina D de aguas altoandinas. B6 y B12 regulan el pico hormonal de la ovulacion." },
      { name: "Ensalada de pallares", reason: "Folato (B9) para division celular. Pallares son leguminosas peruanas ricas en hierro y proteina." },
      { name: "Brocoli saltado con aji", reason: "I3C y DIM para metabolizar pico de estrogeno. Capsaicina del aji tiene propiedades antioxidantes." },
      { name: "Huevos a la peruana", reason: "Colina para integridad celular. Vitamina D y B12. El aji y cebolla aportan antioxidantes." },
      { name: "Sacha inchi (mani del inca)", reason: "48% omega-3, la fuente vegetal mas alta del mundo. Vitamina E protege funcion ovarica. Originario de Peru." },
      { name: "Ensalada de quinoa con verduras", reason: "Proteina completa con folato. Fibra que ayuda al higado a procesar estrogeno. Vitaminas B." },
      { name: "Aguaymanto (physalis peruana)", reason: "Vitamina C y antioxidantes que protegen celulas reproductivas. Polifenoles antiinflamatorios." },
      { name: "Aceitunas de Tacna", reason: "Grasas monoinsaturadas para produccion de progesterona post-ovulacion. Vitamina E. Producto peruano de calidad." },
    ],
    lutea: [
      { name: "Chocolate de cacao chuncho", reason: "Cacao nativo peruano con alto magnesio. Reduce PMS en 33%. Flavonoides superiores al cacao comun." },
      { name: "Camote peruano", reason: "4000+ variedades en Peru. Triptofano para serotonina. Betacarotenos antiinflamatorios contra acne hormonal." },
      { name: "Sopa de quinoa", reason: "Carbohidratos complejos para metabolismo aumentado. Magnesio y triptofano. Plato reconfortante andino." },
      { name: "Yogurt con lucuma", reason: "Calcio reduce PMS. La lucuma aporta betacarotenos y dulzura natural sin picos de azucar." },
      { name: "Mani tostado", reason: "Magnesio y vitamina E reducen hinchazon y sensibilidad mamaria. Muy accesible en mercados peruanos." },
      { name: "Avena con maca y canela", reason: "Maca regula hormonas. Avena da triptofano. Canela estabiliza azucar contra antojos descontrolados." },
      { name: "Menestra de lentejas", reason: "B6 para progesterona. Fibra contra estrenimiento. Hierro prepara reservas para la menstruacion." },
      { name: "Infusion de muña", reason: "Hierba andina con propiedades antiespamodicas y digestivas. Reduce hinchazon y molestias premenstruales." },
    ],
  },

  chile: {
    menstrual: [
      { name: "Cazuela de ave", reason: "Caldo con minerales del hueso. Pollo aporta hierro y proteina. Zapallo y choclo dan carbohidratos reconfortantes." },
      { name: "Cochayuyo guisado", reason: "Alga marina chilena rica en hierro (34mg/100g), yodo y minerales. Unica fuente ancestral de nutrientes marinos." },
      { name: "Porotos granados", reason: "Hierro vegetal, fibra y vitaminas B. Zapallo y maiz aportan betacarotenos. Plato reconfortante chileno." },
      { name: "Mote con huesillo", reason: "Trigo (hierro y B) con durazno deshidratado (potasio y vitamina A). Bebida tradicional nutritiva." },
      { name: "Murtilla (murta)", reason: "Berry nativo del sur de Chile con 4x mas antioxidantes que arandanos. Antiinflamatoria y rica en vitamina C." },
      { name: "Charquican", reason: "Guiso con carne (hierro hemo), papa y zapallo. Magnesio y potasio. Reconfortante durante el periodo." },
      { name: "Naranjas del norte", reason: "Vitamina C del Valle del Elqui aumenta absorcion de hierro. Flavonoides antiinflamatorios." },
      { name: "Pan de campo con palta", reason: "Carbohidratos de masa madre. Grasas de palta para produccion hormonal. Simple y nutritivo." },
    ],
    folicular: [
      { name: "Ceviche chileno", reason: "Pescado fresco (proteina, omega-3) para sintesis muscular. Limon aporta vitamina C. Cebolla morada con quercetina." },
      { name: "Palta reina", reason: "Palta chilena con camarones (zinc, proteina) para desarrollo folicular. Grasas saludables para hormonas." },
      { name: "Brocoli al vapor con merkén", reason: "I3C y DIM para metabolizar estrogeno. El merken (aji ahumado mapuche) tiene capsaicina antioxidante." },
      { name: "Quinoa chilena del altiplano", reason: "Proteina completa con zinc para FSH/LH. Cultivada en el norte de Chile." },
      { name: "Choclo pastel", reason: "Maiz chileno con albahaca y proteina. Carbohidratos complejos para energia sostenida de esta fase." },
      { name: "Yogurt con arandanos del sur", reason: "Probioticos para estroboloma. Arandanos chilenos (exportacion premium) protegen foliculos en desarrollo." },
      { name: "Lentejas con arroz", reason: "Zinc y hierro. Proteina vegetal completa al combinar legumbre + cereal. Plato casero chileno." },
      { name: "Tunas del norte", reason: "Fruta del cactus rica en vitamina C y antioxidantes. Fibra prebiotica para microbioma intestinal." },
    ],
    ovulatoria: [
      { name: "Salmon chileno", reason: "Chile es segundo productor mundial. Omega-3 (EPA/DHA), vitamina D y B12 regulan pico hormonal." },
      { name: "Ensalada chilena (tomate, cebolla)", reason: "Licopeno del tomate protege celulas reproductivas. Quercetina de cebolla es antiinflamatoria." },
      { name: "Huevos con tomate y merkén", reason: "Colina para membranas celulares. Capsaicina del merken tiene propiedades antioxidantes." },
      { name: "Alcachofas al vapor", reason: "Folato (B9) para division celular. Fibra que ayuda al higado a procesar estrogeno. Cultivo chileno." },
      { name: "Almendras del Valle Central", reason: "Vitamina E protege funcion ovarica. Chile produce almendras de calidad en la zona central." },
      { name: "Congrio al horno", reason: "Pescado emblematico chileno. Omega-3, B6 y B12 para regulacion hormonal en el pico ovulatorio." },
      { name: "Ensalada de porotos verdes", reason: "Folato y fibra. Los porotos verdes chilenos son tiernos y ricos en vitaminas del complejo B." },
      { name: "Aceite de oliva del Valle del Huasco", reason: "Grasas monoinsaturadas para produccion de progesterona. Polifenoles. Produccion artesanal chilena." },
    ],
    lutea: [
      { name: "Chocolate artesanal chileno", reason: "Magnesio reduce PMS en 33%. Chocolaterias artesanales chilenas usan cacao de alta calidad." },
      { name: "Sopaipillas pasadas", reason: "Zapallo con triptofano para serotonina. Carbohidratos para metabolismo aumentado. Reconfortante en dias frios." },
      { name: "Platano con manjar", reason: "Potasio reduce retencion de agua. B6 para serotonina. El manjar satisface antojos de forma controlada." },
      { name: "Yogurt con murta", reason: "Calcio reduce PMS. La murta nativa es super-antioxidante y antiinflamatoria. Combinacion unica chilena." },
      { name: "Pan con palta y semillas", reason: "Magnesio de semillas. Grasas de palta. Carbohidratos de pan para combustible. Simple y nutritivo." },
      { name: "Avena con manzana chilena", reason: "Triptofano para serotonina. Manzanas del Maule/O'Higgins aportan pectina y quercetina." },
      { name: "Garbanzos con acelga", reason: "B6 para progesterona. Magnesio de acelga. Fibra contra estrenimiento. Hierro prepara menstruacion." },
      { name: "Infusion de boldo", reason: "Hierba nativa chilena hepatoprotectora. Ayuda al higado a procesar hormonas. Reduce hinchazon." },
    ],
  },

  centroamerica: {
    menstrual: [
      { name: "Frijoles negros volteados", reason: "Hierro vegetal (5mg/taza) y vitaminas B. Base de la dieta centroamericana. Fibra y proteina reconfortante." },
      { name: "Platano cocido con canela", reason: "Potasio reduce calambres. B6 produce serotonina. La canela es antiinflamatoria y estabiliza azucar." },
      { name: "Sopa de gallina india", reason: "Caldo con minerales. Hierro y proteina de la gallina. Verduras locales aportan vitaminas. Tradicion curativa." },
      { name: "Cacao caliente (chocolate)", reason: "Cacao centroamericano (cuna del cacao) con 64mg de magnesio/onza. Serotonina y endorfinas." },
      { name: "Tamal de elote", reason: "Maiz aporta triptofano para serotonina y hierro. Masa reconfortante. Vitaminas B del maiz nixtamalizado." },
      { name: "Chaya (espinaca maya)", reason: "Hierba maya con mas hierro, calcio y proteina que la espinaca. Repone minerales durante sangrado." },
      { name: "Naranja agria con miel", reason: "Vitamina C aumenta absorcion de hierro. Flavonoides antiinflamatorios. Miel aporta minerales traza." },
      { name: "Pepitoria (semillas de calabaza)", reason: "156mg de magnesio por porcion. Zinc y hierro. Snack ancestral mesoamericano para calambres." },
    ],
    folicular: [
      { name: "Chayote guisado", reason: "Folato y zinc para desarrollo folicular. Rico en vitamina C. Muy accesible en toda Centroamerica." },
      { name: "Pollo en recado", reason: "Proteina magra para sintesis muscular. Las especias del recado (achiote, comino) son antiinflamatorias." },
      { name: "Tortillas de maiz con frijol", reason: "Proteina completa al combinar maiz + frijol. Energia sostenida. Zinc para FSH/LH." },
      { name: "Aguacate criollo", reason: "Grasas monoinsaturadas para hormonas. Variedad centroamericana grande y cremosa." },
      { name: "Loroco en pupusa", reason: "Flor comestible salvadorena rica en hierro y calcio. La pupusa de queso aporta proteina." },
      { name: "Jocote (ciruela de huesito)", reason: "Vitamina C y antioxidantes para proteger foliculos. Fruta estacional centroamericana nutritiva." },
      { name: "Pacaya en huevo", reason: "Palmito centroamericano con folato y minerales. El huevo aporta colina y proteina completa." },
      { name: "Licuado de avena con banano", reason: "Carbohidratos complejos para energia. Probioticos si se hace con yogurt. B vitaminas." },
    ],
    ovulatoria: [
      { name: "Pescado frito con tajadas", reason: "Omega-3 y vitamina D del pescado. Platano verde aporta almidon resistente para microbioma." },
      { name: "Brocoli con achiote", reason: "I3C y DIM para estrogeno. El achiote (bija) es antioxidante con betacarotenos." },
      { name: "Huevos estrellados con frijol", reason: "Colina del huevo para membranas celulares. B6 del frijol regula hormonas. Folato para ADN." },
      { name: "Ensalada de repollo y tomate", reason: "Repollo es crucifera con DIM. Tomate aporta licopeno. Limon mejora absorcion de nutrientes." },
      { name: "Semillas de marañon (cashew)", reason: "Centroamerica es origen del marañon. Zinc, magnesio y selenio para tiroides y balance reproductivo." },
      { name: "Elote asado con limon", reason: "Folato para division celular. Vitamina C del limon. Fibra para procesar estrogeno." },
      { name: "Ayote (calabaza) con especias", reason: "Betacarotenos protegen celulas reproductivas. Fibra. Alimento ancestral mesoamericano." },
      { name: "Pepino con limon y chile", reason: "Hidratante con vitamina C. La capsaicina del chile libera endorfinas y es antioxidante." },
    ],
    lutea: [
      { name: "Cacao ceremonial", reason: "Cacao puro centroamericano, cuna del Theobroma cacao. Magnesio reduce PMS. Teobromina mejora animo." },
      { name: "Rellenitos de platano", reason: "Platano maduro con frijol. Triptofano para serotonina. Carbohidratos para metabolismo aumentado." },
      { name: "Arroz con leche", reason: "Calcio de la leche reduce PMS. Triptofano del arroz para serotonina. Canela estabiliza azucar." },
      { name: "Banano maduro con crema", reason: "Potasio reduce retencion de agua. B6 para serotonina. Crema satisface antojos de grasa." },
      { name: "Atol de elote", reason: "Bebida de maiz reconfortante. Triptofano para serotonina. Carbohidratos para energia. Tradicion maya." },
      { name: "Frijoles con arroz (casamiento)", reason: "B6 para progesterona. Proteina completa. Fibra contra estrenimiento. Hierro para menstruacion." },
      { name: "Sopa de frijol negro", reason: "Magnesio y hierro. Fibra contra hinchazon. B vitaminas apoyan progesterona. Reconfortante." },
      { name: "Agua de horchata", reason: "Semilla de jicaro (morro) con calcio y magnesio. Bebida refrescante que reduce hinchazon premenstrual." },
    ],
  },

  espana: {
    menstrual: [
      { name: "Lentejas estofadas", reason: "Plato nacional con 6.6mg hierro/taza. Chorizo aporta hierro hemo. Vitaminas B previenen cambios de humor." },
      { name: "Sardinas en aceite de oliva", reason: "Omega-3 reduce prostaglandinas. Calcio de espinas. Aceite de oliva antiinflamatorio. Tapa clasica." },
      { name: "Chocolate a la taza", reason: "Tradicion espanola con cacao espeso. 64mg magnesio/onza. Serotonina y endorfinas contra dolor menstrual." },
      { name: "Espinacas a la catalana", reason: "Hierro y magnesio. Pinones aportan zinc. Pasas dan hierro adicional. Plato catalan clasico." },
      { name: "Naranjas de Valencia", reason: "Las mejores del mundo. Vitamina C aumenta absorcion de hierro no-hemo. Flavonoides antiinflamatorios." },
      { name: "Pimientos del piquillo rellenos", reason: "Vitamina C (150mg/100g). Relleno de carne da hierro. El pimiento de Navarra es patrimonio gastronomico." },
      { name: "Caldo gallego", reason: "Grelos (hierro, calcio), alubias (proteina, B6) y lacón (hierro hemo). Reconfortante y nutritivo." },
      { name: "Platano de Canarias", reason: "Mas dulce y nutritivo que el comun. Potasio reduce calambres. B6 produce serotonina." },
    ],
    folicular: [
      { name: "Tortilla española", reason: "Huevos (colina, proteina) y patata (energia). Simple, nutritivo y perfecto para esta fase de energia creciente." },
      { name: "Brocoli con jamon iberico", reason: "I3C y DIM del brocoli para estrogeno. El jamon iberico aporta zinc para FSH/LH y proteina." },
      { name: "Garbanzos con espinacas", reason: "Zinc y fibra para estroboloma. Hierro de espinacas. Plato andaluz clasico lleno de nutrientes." },
      { name: "Aceite de oliva virgen extra", reason: "Grasas monoinsaturadas esenciales para hormonas. Polifenoles. Espana es primer productor mundial." },
      { name: "Pavo con verduras asadas", reason: "Proteina magra para sintesis muscular. Verduras mediterraneas aportan antioxidantes y fibra." },
      { name: "Yogurt con fresas de Huelva", reason: "Probioticos para estroboloma. Fresas de Huelva (capital mundial) ricas en vitamina C y antioxidantes." },
      { name: "Arroz integral con verduras", reason: "Carbohidratos complejos para energia sostenida. Fibra y vitaminas B para entrenamientos de fase folicular." },
      { name: "Almendras de Mallorca", reason: "Zinc y vitamina E para desarrollo folicular. Almendras mallorquinas son variedades autóctonas de alta calidad." },
    ],
    ovulatoria: [
      { name: "Merluza a la gallega", reason: "Pescado blanco con omega-3 y B12. Pimenton de la Vera aporta antioxidantes. Patata cachelo da energia." },
      { name: "Ensalada mediterranea", reason: "Tomate (licopeno), pepino, aceitunas (vitamina E), cebolla (quercetina). Protegen celulas reproductivas." },
      { name: "Huevos rotos con jamon", reason: "Colina del huevo para membranas celulares. B12 del jamon. Patata aporta energia para pico hormonal." },
      { name: "Esparragos de Navarra", reason: "Folato (B9) para division celular. Los esparragos de Navarra son Denominacion de Origen. Premium." },
      { name: "Atun rojo de Barbate", reason: "Omega-3, selenio para tiroides, B6 y B12 regulan hormonas. La almadraba es tradicion milenaria." },
      { name: "Gazpacho", reason: "Tomate, pepino, pimiento: licopeno, vitamina C y E. Hidratante. Crudo conserva todos los nutrientes." },
      { name: "Alcachofas de Benicarló", reason: "Folato y fibra para procesar estrogeno. Denominacion de Origen. Hepatoprotectoras." },
      { name: "Pan con tomate y aceite", reason: "Licopeno del tomate. Grasas del AOVE para progesterona. Fibra. Desayuno catalan perfecto." },
    ],
    lutea: [
      { name: "Chocolate con churros", reason: "Magnesio del cacao reduce PMS en 33%. Tradicion espanola. Carbohidratos para metabolismo aumentado." },
      { name: "Pisto manchego", reason: "Verduras (calabacin, pimiento, tomate) con triptofano y vitaminas. Reconfortante. Bajo en calorias." },
      { name: "Batata asada", reason: "Carbohidratos complejos para serotonina via triptofano. Betacarotenos. Popular en otono/invierno espanol." },
      { name: "Yogurt griego con miel", reason: "Calcio (1000mg reduce PMS). Probioticos. La miel espanola aporta minerales y satisface dulzor." },
      { name: "Pipas de girasol", reason: "Espana es gran productor. Magnesio y vitamina E. Snack satisfactorio que reduce hinchazon." },
      { name: "Fabada (version ligera)", reason: "Fabes asturianas con B6 para progesterona. Fibra contra estrenimiento. Hierro prepara menstruacion." },
      { name: "Avena con canela y nueces", reason: "Triptofano para serotonina. Omega-3 de nueces. Canela estabiliza azucar contra antojos." },
      { name: "Infusion de manzanilla", reason: "Apigenina tiene efecto ansiolítico. Antiespasmodica. Mejora el sueno premenstrual. Clasica espanola." },
    ],
  },
};

export function getFoodsForPhase(phaseName, region) {
  if (!region || region === "general") return null;
  return REGIONAL_FOODS[region]?.[phaseName] || null;
}
